import { z } from 'zod'
import { AuditableSchema } from './audit.js'
import { trimmedStringMinMax } from './base-schemas.js'

/**
 * Base schema for LineOfBusiness entity.
 *
 * @public
 */
export const LineOfBusinessBaseSchema = z
	.object({
		id: z.string(),
		name: trimmedStringMinMax(1, 255, 'errors.lineOfBusiness.name.length'),
	})
	.merge(AuditableSchema)
	.describe('Base LineOfBusiness')

/**
 * @public
 */
export type LineOfBusinessBase = z.infer<typeof LineOfBusinessBaseSchema>

/**
 * Expanded schema for LineOfBusiness entity with relationships.
 *
 * @public
 */
export const LineOfBusinessExpandedSchema = LineOfBusinessBaseSchema.extend({
	licenses: z.lazy(() => z.array(z.any())).optional(),
}).describe('Expanded LineOfBusiness with relationships')

/**
 * @public
 */
export type LineOfBusinessExpanded = z.infer<typeof LineOfBusinessExpandedSchema>

/**
 * @public
 */
export type LineOfBusiness = LineOfBusinessExpanded

/**
 * Schema for creating a new LineOfBusiness.
 * Timestamps are auto-generated by the database.
 *
 * @public
 */
export const CreateLineOfBusinessInputSchema = LineOfBusinessBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
	mxid: true,
})

/**
 * @public
 */
export type CreateLineOfBusinessInput = z.infer<typeof CreateLineOfBusinessInputSchema>

/**
 * Schema for updating a LineOfBusiness.
 * Timestamps are auto-updated by the database.
 *
 * @public
 */
export const UpdateLineOfBusinessInputSchema = LineOfBusinessBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
	mxid: true,
}).partial()

/**
 * @public
 */
export type UpdateLineOfBusinessInput = z.infer<typeof UpdateLineOfBusinessInputSchema>

/**
 * Zod schema for validating line of business id path parameter.
 * Validates that id is a positive integer string (bigint PK).
 *
 * @public
 */
export const LineOfBusinessIdParamSchema = z.object({
	id: z
		.string()
		.regex(/^\d+$/, { message: 'errors.lineOfBusiness.id.invalid' })
		.describe('Line of business ID (bigint as string)'),
})

/**
 * TypeScript type for line of business id path parameter.
 *
 * @public
 */
export type LineOfBusinessIdParam = z.infer<typeof LineOfBusinessIdParamSchema>
