import { z } from 'zod'
import { AuditableSchema } from './audit.js'
import { EmailBranded } from '../value-objects/email.js'

/**
 * Base schema for State entity.
 *
 * @public
 */
export const StateBaseSchema = z
	.object({
		id: z.string().uuid(),
		name: z.string().min(1).max(255),
		code: z.string().length(2, { message: 'State code must be exactly 2 characters' }),
		isActive: z.boolean(),
		email: EmailBranded.optional(),
		signatureDistributionEmail: EmailBranded.optional(),
		regionId: z
			.string()
			.regex(/^\d+$/, { message: 'errors.state.regionId.invalid' })
			.describe('Foreign key to region (bigint as string)'),
		countryId: z.number().int(),
	})
	.merge(AuditableSchema)
	.describe('Base State')

/**
 * @public
 */
export type StateBase = z.infer<typeof StateBaseSchema>

/**
 * Expanded schema for State entity with relationships.
 *
 * @public
 */
export const StateExpandedSchema = StateBaseSchema.extend({
	region: z.lazy(() => z.any()).optional(),
	country: z.lazy(() => z.any()).optional(),
	statePrograms: z.lazy(() => z.array(z.any())).optional(),
}).describe('Expanded State with relationships')

/**
 * @public
 */
export type StateExpanded = z.infer<typeof StateExpandedSchema>

/**
 * @public
 */
export type State = StateExpanded

/**
 * Schema for creating a new State.
 * Timestamps are auto-generated by the database.
 *
 * @public
 */
export const CreateStateInputSchema = StateBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
})

/**
 * @public
 */
export type CreateStateInput = z.infer<typeof CreateStateInputSchema>

/**
 * Schema for updating a State.
 * Timestamps are auto-updated by the database.
 *
 * @public
 */
export const UpdateStateInputSchema = StateBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
}).partial()

/**
 * @public
 */
export type UpdateStateInput = z.infer<typeof UpdateStateInputSchema>

/**
 * Zod schema for validating state id path parameter.
 * Reuses validation from StateBaseSchema.shape.id.
 *
 * @public
 */
export const StateIdParamSchema = z.object({
	id: StateBaseSchema.shape.id,
})

/**
 * TypeScript type for state id path parameter.
 *
 * @public
 */
export type StateIdParam = z.infer<typeof StateIdParamSchema>
