import { z } from 'zod'
import { AuditableSchema } from './audit.js'
import { EmailBranded } from '../value-objects/email.js'
import { trimmedStringMinMax } from './base-schemas.js'

/**
 * Helper for state/province codes - trims, uppercases, and validates 2-letter format.
 * @internal
 */
const stateCode = z
	.string()
	.transform((val) => val.trim().toUpperCase())
	.pipe(
		z
			.string()
			.length(2, { message: 'errors.state.code.length' })
			.regex(/^[A-Z]{2}$/, { message: 'errors.state.code.format' }),
	)

/**
 * Base schema for State entity.
 *
 * @public
 */
export const StateBaseSchema = z
	.object({
		id: z.string().uuid(),
		name: trimmedStringMinMax(1, 255, 'errors.state.name.length'),
		code: stateCode.describe('Two-letter state/province code (e.g., CA, TX)'),
		isActive: z.boolean(),
		email: EmailBranded.optional(),
		signatureDistributionEmail: EmailBranded.optional(),
		regionId: z
			.string()
			.regex(/^\d+$/, { message: 'errors.state.regionId.invalid' })
			.describe('Foreign key to region (bigint as string)'),
		countryId: z.number().int(),
	})
	.merge(AuditableSchema)
	.describe('Base State')

/**
 * @public
 */
export type StateBase = z.infer<typeof StateBaseSchema>

/**
 * Expanded schema for State entity with relationships.
 *
 * @public
 */
export const StateExpandedSchema = StateBaseSchema.extend({
	region: z.lazy(() => z.any()).optional(),
	country: z.lazy(() => z.any()).optional(),
	statePrograms: z.lazy(() => z.array(z.any())).optional(),
}).describe('Expanded State with relationships')

/**
 * @public
 */
export type StateExpanded = z.infer<typeof StateExpandedSchema>

/**
 * @public
 */
export type State = StateExpanded

/**
 * Schema for creating a new State.
 * Timestamps are auto-generated by the database.
 *
 * @public
 */
export const CreateStateInputSchema = StateBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
})

/**
 * @public
 */
export type CreateStateInput = z.infer<typeof CreateStateInputSchema>

/**
 * Schema for updating a State.
 * Timestamps are auto-updated by the database.
 *
 * @public
 */
export const UpdateStateInputSchema = StateBaseSchema.omit({
	id: true,
	created: true,
	lastModified: true,
	modifiedBy: true,
}).partial()

/**
 * @public
 */
export type UpdateStateInput = z.infer<typeof UpdateStateInputSchema>

/**
 * Zod schema for validating state id path parameter.
 * Reuses validation from StateBaseSchema.shape.id.
 *
 * @public
 */
export const StateIdParamSchema = z.object({
	id: StateBaseSchema.shape.id,
})

/**
 * TypeScript type for state id path parameter.
 *
 * @public
 */
export type StateIdParam = z.infer<typeof StateIdParamSchema>
