/**
 * RFC 9457 Problem Details (platform standard)
 *
 * Multi-domain strategy:
 * - Use a single canonical base for problem type URIs (decoupled from API host),
 *   e.g. https://problems.exprealty.ai
 * - Keep the key (slug) stable across domains (api.exprealty.ai, agents, etc.).
 * - If you ever need per-domain variants, add a domain prefix to the key
 *   (e.g., "api.validation-error" vs "agents.validation-error") – but prefer
 *   shared keys first.
 */

export interface InvalidParam {
	/** JSON Pointer-ish path or dotted path of the invalid field */
	name: string
	/** Human-readable reason for the validation failure */
	reason: string
	/** Where the param came from (optional hint for clients) */
	in?: 'query' | 'path' | 'header' | 'cookie' | 'body'
}

/**
 * Canonical Problem Details payload per RFC 9457 with exprealty extensions.
 */
export interface ProblemDetails {
	/** A URI reference that identifies the problem type */
	type: string
	/** Short, human-readable summary of the problem type */
	title: string
	/** HTTP status code generated by the origin server for this occurrence */
	status: number
	/** Human-readable explanation specific to this occurrence */
	detail?: string
	/** A URI reference that identifies the specific occurrence */
	instance?: string

	/** exprealty extensions */
	traceId?: string // Correlates with X-Request-Id
	invalidParams?: InvalidParam[] // For 400/422 validation errors

	// Additional RFC 9457 extension members allowed
	[ext: string]: unknown
}

/**
 * Where your problem type URIs live. Keep this independent of API hostnames
 * so you can reuse the same problems across multiple domains/orchestrators.
 *
 * Example values:
 *   - 'https://problems.exprealty.ai'     (recommended)
 *   - 'https://errors.exprealty.ai'
 *   - 'urn:exprealty:problem'             (URNs work, but HTTP URIs are nicer)
 */
export const DEFAULT_PROBLEM_BASE =
	process.env.PROBLEM_BASE?.replace(/\/+$/, '') || 'https://problems.exprealty.ai'

/**
 * Create a canonical problem type URI from a stable key.
 *   makeProblemType('validation-error')
 *   -> 'https://problems.exprealty.ai/validation-error'
 */
export function makeProblemType(key: string): string {
	const base = DEFAULT_PROBLEM_BASE
	const k = key.replace(/^\/+/, '')
	return `${base}/${k}`
}

/**
 * Stable keys used platform-wide. Add new keys here once and reuse everywhere.
 * (Keys are domain-agnostic; the same key is valid for api, agents, etc.)
 */
export const ProblemKeys = {
	Validation: 'validation-error',
	NotFound: 'not-found',
	Unauthorized: 'unauthorized',
	Forbidden: 'forbidden',
	RateLimited: 'rate-limited',
	BadGateway: 'bad-gateway',
	Upstream: 'upstream-error',
	Timeout: 'gateway-timeout',
	Internal: 'internal-error',
	ServiceUnavailable: 'service-unavailable',
} as const

/**
 * Canonical problem type URIs computed from the keys above.
 */
export const ProblemTypes = {
	Validation: makeProblemType(ProblemKeys.Validation),
	NotFound: makeProblemType(ProblemKeys.NotFound),
	Unauthorized: makeProblemType(ProblemKeys.Unauthorized),
	Forbidden: makeProblemType(ProblemKeys.Forbidden),
	RateLimited: makeProblemType(ProblemKeys.RateLimited),
	BadGateway: makeProblemType(ProblemKeys.BadGateway),
	Upstream: makeProblemType(ProblemKeys.Upstream),
	Timeout: makeProblemType(ProblemKeys.Timeout),
	Internal: makeProblemType(ProblemKeys.Internal),
	ServiceUnavailable: makeProblemType(ProblemKeys.ServiceUnavailable),
} as const

/**
 * Sensible default titles for each problem type.
 * (You can override per occurrence if needed.)
 */
export const ProblemTitles: Record<string, string> = {
	[ProblemTypes.Validation]: 'Validation failed',
	[ProblemTypes.NotFound]: 'Not Found',
	[ProblemTypes.Unauthorized]: 'Unauthorized',
	[ProblemTypes.Forbidden]: 'Forbidden',
	[ProblemTypes.RateLimited]: 'Too Many Requests',
	[ProblemTypes.BadGateway]: 'Bad Gateway',
	[ProblemTypes.Upstream]: 'Upstream Error',
	[ProblemTypes.Timeout]: 'Gateway Timeout',
	[ProblemTypes.Internal]: 'Internal Server Error',
	[ProblemTypes.ServiceUnavailable]: 'Service Unavailable',
}

/**
 * Create a fully-formed ProblemDetails object.
 */
export function createProblem(opts: {
	type: string
	status: number
	title?: string
	detail?: string
	instance?: string
	traceId?: string
	invalidParams?: InvalidParam[]
	extensions?: Record<string, unknown>
}): ProblemDetails {
	const title = opts.title ?? ProblemTitles[opts.type]
	const pd: ProblemDetails = {
		type: opts.type,
		title,
		status: opts.status,
		detail: opts.detail,
		instance: opts.instance,
		traceId: opts.traceId,
	}
	if (opts.invalidParams?.length) {
		pd.invalidParams = opts.invalidParams
	}
	if (opts.extensions) {
		Object.assign(pd, opts.extensions)
	}
	return pd
}

/**
 * Convenience creators for common problems.
 */
export const Problems = {
	validation(
		detail: string,
		invalidParams?: InvalidParam[],
		instance?: string,
		traceId?: string,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.Validation,
			status: 400,
			detail,
			instance,
			traceId,
			invalidParams,
		})
	},
	notFound(
		detail = 'No resource matched the request path.',
		instance?: string,
		traceId?: string,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.NotFound,
			status: 404,
			detail,
			instance,
			traceId,
		})
	},
	unauthorized(
		detail = 'Authentication required.',
		instance?: string,
		traceId?: string,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.Unauthorized,
			status: 401,
			detail,
			instance,
			traceId,
		})
	},
	forbidden(
		detail = 'You do not have permission to perform this action.',
		instance?: string,
		traceId?: string,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.Forbidden,
			status: 403,
			detail,
			instance,
			traceId,
		})
	},
	rateLimited(
		detail = 'Too many requests.',
		instance?: string,
		traceId?: string,
		retryAfterSeconds?: number,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.RateLimited,
			status: 429,
			detail,
			instance,
			traceId,
			extensions: retryAfterSeconds ? { retryAfterSeconds } : undefined,
		})
	},
	badGateway(
		detail = 'Failed calling upstream provider.',
		instance?: string,
		traceId?: string,
		ext?: Record<string, unknown>,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.BadGateway,
			status: 502,
			detail,
			instance,
			traceId,
			extensions: ext,
		})
	},
	timeout(
		detail = 'Upstream timed out.',
		instance?: string,
		traceId?: string,
		ext?: Record<string, unknown>,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.Timeout,
			status: 504,
			detail,
			instance,
			traceId,
			extensions: ext,
		})
	},
	internal(
		detail = 'An unexpected error occurred.',
		instance?: string,
		traceId?: string,
		ext?: Record<string, unknown>,
	): ProblemDetails {
		return createProblem({
			type: ProblemTypes.Internal,
			status: 500,
			detail,
			instance,
			traceId,
			extensions: ext,
		})
	},
}

/**
 * Extension for upstream provider errors.
 * Used when orchestrator encounters errors calling downstream services.
 */
export interface UpstreamExtension {
	/** Details about the upstream service that failed */
	upstream?: {
		/** Error code (e.g., ECONNABORTED, ENOTFOUND) */
		code?: string
		/** URL that was called */
		url?: string
		/** HTTP method used */
		method?: string
		/** HTTP status code returned by the provider (if any) */
		providerStatus: number | null
	}
}

/**
 * Problem Details with upstream service error information.
 */
export type UpstreamProblemDetails = ProblemDetails & UpstreamExtension

/**
 * Type guard to detect an object that looks like ProblemDetails.
 */
export function isProblemDetails(x: unknown): x is ProblemDetails {
	return (
		!!x &&
		typeof x === 'object' &&
		'type' in (x as Record<string, unknown>) &&
		'title' in (x as Record<string, unknown>) &&
		'status' in (x as Record<string, unknown>)
	)
}
