import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1762356356157 implements MigrationInterface {
    name = 'InitialSchema1762356356157'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE SCHEMA IF NOT EXISTS core;`);
        await queryRunner.query(`CREATE TABLE "core"."address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "line1" text NOT NULL, "line2" text, "city" text NOT NULL, "unit" text NOT NULL, "postal_code" text NOT NULL, "country" character(2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "legacy_id" uuid NOT NULL, "email" text NOT NULL, "name" text NOT NULL, "phone" text NOT NULL, "tax_id" text, "tax_id_hashed" text, "use_ssn" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_222e1946725ccea0674ecf75b2e" UNIQUE ("email"), CONSTRAINT "PK_81fca3f58e8f54e10c46adb07d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_id" bigint, "title" text, "first_name" text NOT NULL, "middle_name" text, "last_name" text NOT NULL, "suffix" text, "preferred_name" text, "birth_date" TIMESTAMP WITH TIME ZONE, "lifecycle_status" text, "last_modified" TIMESTAMP WITH TIME ZONE, "system_id" integer, "seed_agent" boolean NOT NULL DEFAULT false, "join_date" TIMESTAMP WITH TIME ZONE, "anniversary_date" TIMESTAMP WITH TIME ZONE, "termination_date" TIMESTAMP WITH TIME ZONE, "is_staff" boolean NOT NULL DEFAULT false, "agent_company_id" uuid NOT NULL, CONSTRAINT "PK_1000e989398c5d4ed585cf9a46f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_id" uuid NOT NULL, "address_id" uuid NOT NULL, "role" character varying(20), "is_primary" boolean NOT NULL DEFAULT false, "valid_from" date, "valid_to" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7b8b0514632bffdf8d13afbc9de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."company" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "email" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_b0fc567cf51b1cf717a9e8046a1" UNIQUE ("email"), CONSTRAINT "PK_056f7854a7afdba7cbd6d45fc20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."office" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "office_id" bigint NOT NULL, "website" text, "name" text NOT NULL, "phone" text NOT NULL, "lifecycle_status" text NOT NULL, "primary_state" character varying(200) NOT NULL, CONSTRAINT "PK_200185316ba169fda17e3b6ba00" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."external_reference" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "system_code" text NOT NULL, "ref_key" text NOT NULL, "ref_value" text NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_02611658e0d81ce42303ab9ab90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_external_reference" ("agent_id" uuid NOT NULL, "external_reference_id" uuid NOT NULL, CONSTRAINT "PK_779b87a2e3cb41adc63b014852b" PRIMARY KEY ("agent_id", "external_reference_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."office_external_reference" ("office_id" uuid NOT NULL, "external_reference_id" uuid NOT NULL, CONSTRAINT "PK_625031fa773b30175e134c748e2" PRIMARY KEY ("office_id", "external_reference_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."company_external_reference" ("company_id" uuid NOT NULL, "external_reference_id" uuid NOT NULL, CONSTRAINT "PK_200241f196ec4223ba9ac05784f" PRIMARY KEY ("company_id", "external_reference_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_office" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_primary" boolean NOT NULL, "agent_id" uuid NOT NULL, "office_id" uuid NOT NULL, CONSTRAINT "PK_93b7fd326a55886fd710554e002" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."pay_plan" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "active" boolean NOT NULL, "agent_percentage" numeric NOT NULL, "cap" numeric NOT NULL, CONSTRAINT "PK_045653ccd9e77d0113555158a50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."payment_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_id" uuid NOT NULL, "pay_plan_id" uuid, "cap_reset_date" TIMESTAMP WITH TIME ZONE NOT NULL, "split_check" boolean NOT NULL, "cap_reset_date_changed_by_user" boolean NOT NULL, CONSTRAINT "PK_78624861ce2178d6835fb1d9fdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."payment_settings_variant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_settings" uuid NOT NULL, "custom_name" text NOT NULL, "value" numeric NOT NULL, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "type" text NOT NULL, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_8ac543d2cddcf990f692984b917" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."plan_variant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_settings" uuid NOT NULL, "name" text NOT NULL, "default_value" numeric NOT NULL, "is_default" boolean NOT NULL, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_0b62512c4a6c0945084a77e4e1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."pay_plan_variant" ("variant_id" character varying NOT NULL, "pay_plan_id" uuid NOT NULL, "value" numeric NOT NULL, CONSTRAINT "PK_bb836ce1d1d99ad8d87a30ad9c9" PRIMARY KEY ("variant_id", "pay_plan_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."language" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "code" text NOT NULL, "supported" boolean NOT NULL, CONSTRAINT "PK_cc0a99e710eb3733f6fb42b1d4c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_language" ("agent_id" uuid NOT NULL, "language_id" uuid NOT NULL, CONSTRAINT "PK_8842aab9c9a91b69f92aa477284" PRIMARY KEY ("agent_id", "language_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."public_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "agent_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cbc966fdb35f93df14e23be606f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."contact_method" ("id" SERIAL NOT NULL, "name" text NOT NULL, "channel" text NOT NULL, "sub_type" text, "value" text NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, "sms_opt_in" boolean, "agent_id" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ee65af2b1bc0c820a934549b8ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."email_forward" ("id" SERIAL NOT NULL, "recipient_id" text NOT NULL, "verified_last_checked" TIMESTAMP WITH TIME ZONE, "verified" boolean NOT NULL DEFAULT false, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "forward_id" text NOT NULL, "recipient_created" TIMESTAMP WITH TIME ZONE, "verified_date" TIMESTAMP WITH TIME ZONE, "language" text, CONSTRAINT "PK_734c0c3095c261b10af0ef66c0d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."social" ("id" SERIAL NOT NULL, "context" text NOT NULL, "value" text NOT NULL, CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."specialty" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "PK_9cf4ae334dc4a1ab1e08956460e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_specialty" ("agent_uuid" uuid NOT NULL, "public_profile_id" uuid NOT NULL, "specialty_id" bigint NOT NULL, CONSTRAINT "PK_44e0e62141ba0c5ef301911d73d" PRIMARY KEY ("agent_uuid", "public_profile_id", "specialty_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."mls" ("mlsId" BIGSERIAL NOT NULL, "ouid" text, "global_id" integer, "lifecycle_status" text NOT NULL, "name" text NOT NULL, "short_name" text, "website" text, "org_type" text NOT NULL, "larversion_url" text, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, "modified_by" text NOT NULL, "address_id" uuid, CONSTRAINT "PK_305dab3fd4701ed4e20a909882d" PRIMARY KEY ("mlsId"))`);
        await queryRunner.query(`CREATE TABLE "core"."agent_mls" ("agent_id" uuid NOT NULL, "mls_id" bigint NOT NULL, CONSTRAINT "PK_6456ca7bc0bf569622f7edef94c" PRIMARY KEY ("agent_id", "mls_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."active_location" ("name" text NOT NULL, "agent_id" uuid NOT NULL, "postal_code" text NOT NULL, "city" text NOT NULL, "is_primary" boolean NOT NULL, CONSTRAINT "PK_4b916ae5038c6500269ffb9bf75" PRIMARY KEY ("name", "agent_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."line_of_business" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "PK_38eeccc38228d3292b3b17d7bb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."license" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "expiration_date" date, "is_primary" boolean NOT NULL, "type" character varying(50) NOT NULL, "first_name" text NOT NULL, "middle_name" text, "last_name" text NOT NULL, "suffix" text, "number" text NOT NULL, "line_of_business_id" bigint NOT NULL, "state_id" uuid NOT NULL, CONSTRAINT "PK_f168ac1ca5ba87286d03b2ef905" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."note" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor" text NOT NULL, "body" text NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_96d0c172a4fba276b1bbed43058" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."lifecycle_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor" text NOT NULL, "effective_date" TIMESTAMP WITH TIME ZONE NOT NULL, "type" text NOT NULL, "active" boolean NOT NULL, "note_id" uuid, CONSTRAINT "PK_b177ca4094a0ad252a3d4fbe1db" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."license_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "license_id" uuid NOT NULL, "actor" text NOT NULL, "date" TIMESTAMP WITH TIME ZONE NOT NULL, "type" text NOT NULL, "status" text NOT NULL, CONSTRAINT "PK_231e1b96cadf77c359ab5e29aa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."relationship" ("subject_agent_id" uuid NOT NULL, "object_agent_id" uuid NOT NULL, "type" text NOT NULL, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_e007321642d496398c3061b8a0f" PRIMARY KEY ("subject_agent_id", "object_agent_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."sponsor_configuration" ("agent_id" uuid NOT NULL, "uuid" uuid NOT NULL, "buffer" integer NOT NULL, "sponsor_buffer_override" boolean NOT NULL, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_3bd437c9c4156a640041aada603" PRIMARY KEY ("agent_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."country" ("country_id" SERIAL NOT NULL, "name" text NOT NULL, "alpha_2" character varying(2) NOT NULL, "alpha_3" character varying(3) NOT NULL, "number" integer NOT NULL, "dialing_code" integer NOT NULL, CONSTRAINT "UQ_2cba84a119181c84721bdfcb559" UNIQUE ("alpha_2"), CONSTRAINT "UQ_37ef805396783b4cb210931c32e" UNIQUE ("alpha_3"), CONSTRAINT "UQ_9b0f16e109c6741810c08f99ebf" UNIQUE ("number"), CONSTRAINT "PK_220fe368500f103cf873b01f159" PRIMARY KEY ("country_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."region" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, CONSTRAINT "PK_5f48ffc3af96bc486f5f3f3a6da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."state" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "code" text NOT NULL, "is_active" boolean NOT NULL, "email" text, "signature_distribution_email" text, "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL, "modified_by" text NOT NULL, "region_id" bigint NOT NULL, CONSTRAINT "PK_549ffd046ebab1336c3a8030a12" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."program" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, CONSTRAINT "PK_3bade5945afbafefdd26a3a29fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."state_program" ("state_id" uuid NOT NULL, "program_id" uuid NOT NULL, CONSTRAINT "PK_34616f86d0ce70cf7a2fa3b3a69" PRIMARY KEY ("state_id", "program_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."organization_contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" text NOT NULL, "email" text, "phone" text, "address" text, CONSTRAINT "PK_1b315ca37fec4b8bdbdf1b59d28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."w9" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tin" text NOT NULL, "legal_name" text NOT NULL, "business_name" text, "federal_tax_classification" text NOT NULL, "federal_tax_classification_other" text, "exempt_payee_code" text, "exemption_from_fatca_reporting_code" text, "signature_date" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_5879bda5407305a0b5efc98234a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."w9_address" ("w9_id" uuid NOT NULL, "address_id" uuid NOT NULL, CONSTRAINT "PK_77691a4ca50a7d82515aff38536" PRIMARY KEY ("w9_id", "address_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."tax" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tax_id" text NOT NULL, "type" text NOT NULL, "jurisdiction" text NOT NULL, "rate" numeric(10,4), "effective_date" TIMESTAMP WITH TIME ZONE, "expiration_date" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2c1e62c595571139e2fb0e9c319" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."office_address" ("office_id" uuid NOT NULL, "address_id" uuid NOT NULL, CONSTRAINT "PK_cf2885779369d5f8aedefa01285" PRIMARY KEY ("office_id", "address_id"))`);
        await queryRunner.query(`CREATE TABLE "core"."artifact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" text NOT NULL, "name" text NOT NULL, "url" text, "storage_key" text, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1f238d1d4ef8f85d0c0b8616fa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."custom_flag" ("flagId" BIGSERIAL NOT NULL, "name" text NOT NULL, "type" text NOT NULL, "scope" text NOT NULL, "active" boolean NOT NULL, "delete_in_progress" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_6da375da9920e2e2969998b3ae5" PRIMARY KEY ("flagId"))`);
        await queryRunner.query(`CREATE TABLE "core"."fee" ("id" BIGSERIAL NOT NULL, "name" text NOT NULL, "active" boolean NOT NULL, "value" numeric(10,2) NOT NULL, "paid_by" text, "is_third_party" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_ee7e51cc563615bc60c2b234635" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "core"."approval" ("approvalId" BIGSERIAL NOT NULL, "approval_state" text NOT NULL, "decision_date" TIMESTAMP WITH TIME ZONE, "counters" integer, "template" text, "note" text, "prerequisite" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_02de44a875038b4b24888b7df16" PRIMARY KEY ("approvalId"))`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ADD CONSTRAINT "FK_14ce21569e369a956eb6ddb2418" FOREIGN KEY ("agent_company_id") REFERENCES "core"."agent_company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_address" ADD CONSTRAINT "FK_ed7593c82395637aae5cf16b8a1" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_address" ADD CONSTRAINT "FK_d3f14a22292694dfea3c4a76ce0" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_external_reference" ADD CONSTRAINT "FK_06901b006017fd684530a1e83be" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_external_reference" ADD CONSTRAINT "FK_371e073358b18d22272471303f3" FOREIGN KEY ("external_reference_id") REFERENCES "core"."external_reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_bf9d6c6c7c8ce63e0326f4a51b4" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_21ff193616770559463efbf0396" FOREIGN KEY ("external_reference_id") REFERENCES "core"."external_reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."company_external_reference" ADD CONSTRAINT "FK_7bd4e4fea1796610564375c3c08" FOREIGN KEY ("company_id") REFERENCES "core"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."company_external_reference" ADD CONSTRAINT "FK_a68028cbd877226314c8ca64e3a" FOREIGN KEY ("external_reference_id") REFERENCES "core"."external_reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_f5ec523ddd694262dfccc237284" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_a9e9433cfd2dda289a647c12c45" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings" ADD CONSTRAINT "FK_c6c5a8a6ed6f2e305f9d6a5c59d" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings" ADD CONSTRAINT "FK_7a2c7a6c88abf797930ffc653ea" FOREIGN KEY ("pay_plan_id") REFERENCES "core"."pay_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings_variant" ADD CONSTRAINT "FK_2bb8dceb306b3665661162ab7f7" FOREIGN KEY ("payment_settings") REFERENCES "core"."payment_settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan_variant" ADD CONSTRAINT "FK_8decb671307ed20ad34ee9860bf" FOREIGN KEY ("pay_plan_id") REFERENCES "core"."pay_plan"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_language" ADD CONSTRAINT "FK_655274b2246207a662e3940b0d4" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_language" ADD CONSTRAINT "FK_c58ded607e284db17d03e9eb20b" FOREIGN KEY ("language_id") REFERENCES "core"."language"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD CONSTRAINT "FK_eecbfbc7a84edead08eb36569a0" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."contact_method" ADD CONSTRAINT "FK_9f5089b30e8bed603cb632c1292" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" ADD CONSTRAINT "FK_45f4f33bd107799801e5b58cfaa" FOREIGN KEY ("agent_uuid") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" ADD CONSTRAINT "FK_8a2867d41502fcf87b7f86b9435" FOREIGN KEY ("public_profile_id") REFERENCES "core"."public_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" ADD CONSTRAINT "FK_603cf1d694df3553853a64f7700" FOREIGN KEY ("specialty_id") REFERENCES "core"."specialty"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ADD CONSTRAINT "FK_7074a63c12a6454117ad5c3f3a3" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" ADD CONSTRAINT "FK_65aaa3aaf76c2e3a557e4b72bc7" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" ADD CONSTRAINT "FK_b0f6195e4793254861d50da989a" FOREIGN KEY ("mls_id") REFERENCES "core"."mls"("mlsId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."active_location" ADD CONSTRAINT "FK_7c84c989350ac029668479b6933" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD CONSTRAINT "FK_289562756cc37e8d157d1f765ff" FOREIGN KEY ("line_of_business_id") REFERENCES "core"."line_of_business"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."lifecycle_event" ADD CONSTRAINT "FK_e4505f8f9ac2216166bdec75cc9" FOREIGN KEY ("note_id") REFERENCES "core"."note"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."license_event" ADD CONSTRAINT "FK_8af0ee4cdd3e606b0912283ff2c" FOREIGN KEY ("license_id") REFERENCES "core"."license"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."relationship" ADD CONSTRAINT "FK_02daa286e72a57e9827ff64580f" FOREIGN KEY ("subject_agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."relationship" ADD CONSTRAINT "FK_8c55ce25553956a1f009b5beda9" FOREIGN KEY ("object_agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."sponsor_configuration" ADD CONSTRAINT "FK_3bd437c9c4156a640041aada603" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state" ADD CONSTRAINT "FK_8349ce36d37d8f89fd9dc8fa002" FOREIGN KEY ("region_id") REFERENCES "core"."region"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" ADD CONSTRAINT "FK_a9ec7704f7c2a41971e32f37629" FOREIGN KEY ("state_id") REFERENCES "core"."state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" ADD CONSTRAINT "FK_e7e44a9cccc1cf53b320659d265" FOREIGN KEY ("program_id") REFERENCES "core"."program"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."w9_address" ADD CONSTRAINT "FK_354b1ce03fc57661b01ed3fb54f" FOREIGN KEY ("w9_id") REFERENCES "core"."w9"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."w9_address" ADD CONSTRAINT "FK_74a7167ce3bb8d99e684ba5f245" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_f43f4200662b0ce7beddd29c3f5" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_78be10b4116a9772d6f763c4301" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_78be10b4116a9772d6f763c4301"`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_f43f4200662b0ce7beddd29c3f5"`);
        await queryRunner.query(`ALTER TABLE "core"."w9_address" DROP CONSTRAINT "FK_74a7167ce3bb8d99e684ba5f245"`);
        await queryRunner.query(`ALTER TABLE "core"."w9_address" DROP CONSTRAINT "FK_354b1ce03fc57661b01ed3fb54f"`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" DROP CONSTRAINT "FK_e7e44a9cccc1cf53b320659d265"`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" DROP CONSTRAINT "FK_a9ec7704f7c2a41971e32f37629"`);
        await queryRunner.query(`ALTER TABLE "core"."state" DROP CONSTRAINT "FK_8349ce36d37d8f89fd9dc8fa002"`);
        await queryRunner.query(`ALTER TABLE "core"."sponsor_configuration" DROP CONSTRAINT "FK_3bd437c9c4156a640041aada603"`);
        await queryRunner.query(`ALTER TABLE "core"."relationship" DROP CONSTRAINT "FK_8c55ce25553956a1f009b5beda9"`);
        await queryRunner.query(`ALTER TABLE "core"."relationship" DROP CONSTRAINT "FK_02daa286e72a57e9827ff64580f"`);
        await queryRunner.query(`ALTER TABLE "core"."license_event" DROP CONSTRAINT "FK_8af0ee4cdd3e606b0912283ff2c"`);
        await queryRunner.query(`ALTER TABLE "core"."lifecycle_event" DROP CONSTRAINT "FK_e4505f8f9ac2216166bdec75cc9"`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP CONSTRAINT "FK_289562756cc37e8d157d1f765ff"`);
        await queryRunner.query(`ALTER TABLE "core"."active_location" DROP CONSTRAINT "FK_7c84c989350ac029668479b6933"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" DROP CONSTRAINT "FK_b0f6195e4793254861d50da989a"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" DROP CONSTRAINT "FK_65aaa3aaf76c2e3a557e4b72bc7"`);
        await queryRunner.query(`ALTER TABLE "core"."mls" DROP CONSTRAINT "FK_7074a63c12a6454117ad5c3f3a3"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" DROP CONSTRAINT "FK_603cf1d694df3553853a64f7700"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" DROP CONSTRAINT "FK_8a2867d41502fcf87b7f86b9435"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_specialty" DROP CONSTRAINT "FK_45f4f33bd107799801e5b58cfaa"`);
        await queryRunner.query(`ALTER TABLE "core"."contact_method" DROP CONSTRAINT "FK_9f5089b30e8bed603cb632c1292"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP CONSTRAINT "FK_eecbfbc7a84edead08eb36569a0"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_language" DROP CONSTRAINT "FK_c58ded607e284db17d03e9eb20b"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_language" DROP CONSTRAINT "FK_655274b2246207a662e3940b0d4"`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan_variant" DROP CONSTRAINT "FK_8decb671307ed20ad34ee9860bf"`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings_variant" DROP CONSTRAINT "FK_2bb8dceb306b3665661162ab7f7"`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings" DROP CONSTRAINT "FK_7a2c7a6c88abf797930ffc653ea"`);
        await queryRunner.query(`ALTER TABLE "core"."payment_settings" DROP CONSTRAINT "FK_c6c5a8a6ed6f2e305f9d6a5c59d"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_a9e9433cfd2dda289a647c12c45"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_f5ec523ddd694262dfccc237284"`);
        await queryRunner.query(`ALTER TABLE "core"."company_external_reference" DROP CONSTRAINT "FK_a68028cbd877226314c8ca64e3a"`);
        await queryRunner.query(`ALTER TABLE "core"."company_external_reference" DROP CONSTRAINT "FK_7bd4e4fea1796610564375c3c08"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_21ff193616770559463efbf0396"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_bf9d6c6c7c8ce63e0326f4a51b4"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_external_reference" DROP CONSTRAINT "FK_371e073358b18d22272471303f3"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_external_reference" DROP CONSTRAINT "FK_06901b006017fd684530a1e83be"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_address" DROP CONSTRAINT "FK_d3f14a22292694dfea3c4a76ce0"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_address" DROP CONSTRAINT "FK_ed7593c82395637aae5cf16b8a1"`);
        await queryRunner.query(`ALTER TABLE "core"."agent" DROP CONSTRAINT "FK_14ce21569e369a956eb6ddb2418"`);
        await queryRunner.query(`DROP TABLE "core"."approval"`);
        await queryRunner.query(`DROP TABLE "core"."fee"`);
        await queryRunner.query(`DROP TABLE "core"."custom_flag"`);
        await queryRunner.query(`DROP TABLE "core"."artifact"`);
        await queryRunner.query(`DROP TABLE "core"."office_address"`);
        await queryRunner.query(`DROP TABLE "core"."tax"`);
        await queryRunner.query(`DROP TABLE "core"."w9_address"`);
        await queryRunner.query(`DROP TABLE "core"."w9"`);
        await queryRunner.query(`DROP TABLE "core"."organization_contact"`);
        await queryRunner.query(`DROP TABLE "core"."state_program"`);
        await queryRunner.query(`DROP TABLE "core"."program"`);
        await queryRunner.query(`DROP TABLE "core"."state"`);
        await queryRunner.query(`DROP TABLE "core"."region"`);
        await queryRunner.query(`DROP TABLE "core"."country"`);
        await queryRunner.query(`DROP TABLE "core"."sponsor_configuration"`);
        await queryRunner.query(`DROP TABLE "core"."relationship"`);
        await queryRunner.query(`DROP TABLE "core"."license_event"`);
        await queryRunner.query(`DROP TABLE "core"."lifecycle_event"`);
        await queryRunner.query(`DROP TABLE "core"."note"`);
        await queryRunner.query(`DROP TABLE "core"."license"`);
        await queryRunner.query(`DROP TABLE "core"."line_of_business"`);
        await queryRunner.query(`DROP TABLE "core"."active_location"`);
        await queryRunner.query(`DROP TABLE "core"."agent_mls"`);
        await queryRunner.query(`DROP TABLE "core"."mls"`);
        await queryRunner.query(`DROP TABLE "core"."agent_specialty"`);
        await queryRunner.query(`DROP TABLE "core"."specialty"`);
        await queryRunner.query(`DROP TABLE "core"."social"`);
        await queryRunner.query(`DROP TABLE "core"."email_forward"`);
        await queryRunner.query(`DROP TABLE "core"."contact_method"`);
        await queryRunner.query(`DROP TABLE "core"."public_profile"`);
        await queryRunner.query(`DROP TABLE "core"."agent_language"`);
        await queryRunner.query(`DROP TABLE "core"."language"`);
        await queryRunner.query(`DROP TABLE "core"."pay_plan_variant"`);
        await queryRunner.query(`DROP TABLE "core"."plan_variant"`);
        await queryRunner.query(`DROP TABLE "core"."payment_settings_variant"`);
        await queryRunner.query(`DROP TABLE "core"."payment_settings"`);
        await queryRunner.query(`DROP TABLE "core"."pay_plan"`);
        await queryRunner.query(`DROP TABLE "core"."agent_office"`);
        await queryRunner.query(`DROP TABLE "core"."company_external_reference"`);
        await queryRunner.query(`DROP TABLE "core"."office_external_reference"`);
        await queryRunner.query(`DROP TABLE "core"."agent_external_reference"`);
        await queryRunner.query(`DROP TABLE "core"."external_reference"`);
        await queryRunner.query(`DROP TABLE "core"."office"`);
        await queryRunner.query(`DROP TABLE "core"."company"`);
        await queryRunner.query(`DROP TABLE "core"."agent_address"`);
        await queryRunner.query(`DROP TABLE "core"."agent"`);
        await queryRunner.query(`DROP TABLE "core"."agent_company"`);
        await queryRunner.query(`DROP TABLE "core"."address"`);
    }

}
