import { MigrationInterface, QueryRunner } from "typeorm";

export class AddEntityFieldsAndRelationships1765813354156 implements MigrationInterface {
    name = 'AddEntityFieldsAndRelationships1765813354156'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."office" DROP CONSTRAINT "FK_office_company"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_office_ext_ref_external_reference"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_office_ext_ref_office"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_agent_office_office"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_agent_office_agent"`);
        await queryRunner.query(`ALTER TABLE "core"."state" DROP CONSTRAINT "fk_state_country"`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" DROP CONSTRAINT "FK_state_program_state"`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" DROP CONSTRAINT "FK_state_program_program"`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_office_address_address"`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_office_address_office"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_office_company_id"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_office_lifecycle_status"`);
        await queryRunner.query(`DROP INDEX "core"."IDX_office_name"`);
        await queryRunner.query(`DROP INDEX "core"."idx_state_country_id"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "signature_date"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "tin"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "legal_name"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "business_name"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "federal_tax_classification"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "federal_tax_classification_other"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "exemption_from_fatca_reporting_code"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "storage_key"`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "first_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "last_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "email" text`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "phone" text`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "show_title" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "bio" text`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "last_sync" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "exclude_from_public" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ADD "agent_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "public_profile_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "status" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "account_number" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "collection_source" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "tax_reporting_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "tax_classification" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "llc_tax_classification" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "disregarded_entity_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "document_id" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "document_url" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "total_submission_attempts" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "fatca_reporting_codes" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "compliancely_result" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "compliancely_tax_reporting_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "created" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "last_modified" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "modified_by" text NOT NULL DEFAULT 'system'`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "agent_id" bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ALTER COLUMN "last_modified" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ALTER COLUMN "last_modified" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan" ALTER COLUMN "agent_percentage" TYPE numeric(5,2)`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan" ALTER COLUMN "cap" TYPE numeric(10,2)`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ALTER COLUMN "created" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "id" BIGSERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" DROP CONSTRAINT "FK_b0f6195e4793254861d50da989a"`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "last_modified" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "modified_by" SET DEFAULT 'system'`);
        await queryRunner.query(`CREATE SEQUENCE IF NOT EXISTS "core"."mls_id_seq" OWNED BY "core"."mls"."id"`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "id" SET DEFAULT nextval('"core"."mls_id_seq"')`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "expiration_date"`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "expiration_date" TIMESTAMP WITH TIME ZONE`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "type" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."program" DROP CONSTRAINT "UQ_program_code"`);
        await queryRunner.query(`ALTER TABLE "core"."office" ADD CONSTRAINT "FK_1d2c5ae4f7c50107b361335279d" FOREIGN KEY ("company_id") REFERENCES "core"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_bf9d6c6c7c8ce63e0326f4a51b4" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_21ff193616770559463efbf0396" FOREIGN KEY ("external_reference_id") REFERENCES "core"."external_reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_f5ec523ddd694262dfccc237284" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_a9e9433cfd2dda289a647c12c45" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ADD CONSTRAINT "FK_77247af9720e1d4eded98f3424c" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD CONSTRAINT "FK_7834644a5255770ac759073cadb" FOREIGN KEY ("public_profile_id") REFERENCES "core"."public_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" ADD CONSTRAINT "FK_b0f6195e4793254861d50da989a" FOREIGN KEY ("mls_id") REFERENCES "core"."mls"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD CONSTRAINT "FK_c6e3904af365b8e3fb87e0afa66" FOREIGN KEY ("state_id") REFERENCES "core"."state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state" ADD CONSTRAINT "FK_dd19065b0813dbffd8170ea6753" FOREIGN KEY ("country_id") REFERENCES "core"."country"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" ADD CONSTRAINT "FK_e7e44a9cccc1cf53b320659d265" FOREIGN KEY ("program_id") REFERENCES "core"."program"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_f43f4200662b0ce7beddd29c3f5" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_78be10b4116a9772d6f763c4301" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        // Add unique constraint on agent.agent_id before creating FK that references it
        await queryRunner.query(`ALTER TABLE "core"."agent" ADD CONSTRAINT "UQ_agent_agent_id" UNIQUE ("agent_id")`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD CONSTRAINT "FK_e19c0ef843d6873b96b4b1cf134" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("agent_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP CONSTRAINT "FK_e19c0ef843d6873b96b4b1cf134"`);
        await queryRunner.query(`ALTER TABLE "core"."agent" DROP CONSTRAINT "UQ_agent_agent_id"`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_78be10b4116a9772d6f763c4301"`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" DROP CONSTRAINT "FK_f43f4200662b0ce7beddd29c3f5"`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" DROP CONSTRAINT "FK_e7e44a9cccc1cf53b320659d265"`);
        await queryRunner.query(`ALTER TABLE "core"."state" DROP CONSTRAINT "FK_dd19065b0813dbffd8170ea6753"`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP CONSTRAINT "FK_c6e3904af365b8e3fb87e0afa66"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" DROP CONSTRAINT "FK_b0f6195e4793254861d50da989a"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP CONSTRAINT "FK_7834644a5255770ac759073cadb"`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" DROP CONSTRAINT "FK_77247af9720e1d4eded98f3424c"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_a9e9433cfd2dda289a647c12c45"`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" DROP CONSTRAINT "FK_f5ec523ddd694262dfccc237284"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_21ff193616770559463efbf0396"`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" DROP CONSTRAINT "FK_bf9d6c6c7c8ce63e0326f4a51b4"`);
        await queryRunner.query(`ALTER TABLE "core"."office" DROP CONSTRAINT "FK_1d2c5ae4f7c50107b361335279d"`);
        await queryRunner.query(`ALTER TABLE "core"."program" ADD CONSTRAINT "UQ_program_code" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "type" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "expiration_date"`);
        await queryRunner.query(`ALTER TABLE "core"."license" ADD "expiration_date" date`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "id" SET DEFAULT nextval('core."mls_mlsId_seq"')`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`DROP SEQUENCE "core"."mls_id_seq"`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "modified_by" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "core"."mls" ALTER COLUMN "last_modified" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "core"."agent_mls" ADD CONSTRAINT "FK_b0f6195e4793254861d50da989a" FOREIGN KEY ("mls_id") REFERENCES "core"."mls"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."social" ADD CONSTRAINT "PK_645aa1cff2b9f7b0e3e73d66b4d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" ALTER COLUMN "created" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan" ALTER COLUMN "cap" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "core"."pay_plan" ALTER COLUMN "agent_percentage" TYPE numeric`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ALTER COLUMN "last_modified" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "core"."agent" ALTER COLUMN "last_modified" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "agent_id"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "compliancely_tax_reporting_name"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "compliancely_result"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "fatca_reporting_codes"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "total_submission_attempts"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "document_url"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "document_id"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "disregarded_entity_name"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "llc_tax_classification"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "tax_classification"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "tax_reporting_name"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "collection_source"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "account_number"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."w9" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."license" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "public_profile_id"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."social" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" DROP COLUMN "agent_id"`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."email_forward" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "exclude_from_public"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "last_sync"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "bio"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "show_title"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "phone"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "last_name"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "first_name"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "last_modified"`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."agent" DROP COLUMN "modified_by"`);
        await queryRunner.query(`ALTER TABLE "core"."agent" DROP COLUMN "created"`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "storage_key" text`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."artifact" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "exemption_from_fatca_reporting_code" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "federal_tax_classification_other" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "federal_tax_classification" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "business_name" text`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "legal_name" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "tin" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."w9" ADD "signature_date" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "core"."public_profile" ADD "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE INDEX "idx_state_country_id" ON "core"."state" ("country_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_office_name" ON "core"."office" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_office_lifecycle_status" ON "core"."office" ("lifecycle_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_office_company_id" ON "core"."office" ("company_id") `);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_office_address_office" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_address" ADD CONSTRAINT "FK_office_address_address" FOREIGN KEY ("address_id") REFERENCES "core"."address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" ADD CONSTRAINT "FK_state_program_program" FOREIGN KEY ("program_id") REFERENCES "core"."program"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state_program" ADD CONSTRAINT "FK_state_program_state" FOREIGN KEY ("state_id") REFERENCES "core"."state"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."state" ADD CONSTRAINT "fk_state_country" FOREIGN KEY ("country_id") REFERENCES "core"."country"("id") ON DELETE RESTRICT ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_agent_office_agent" FOREIGN KEY ("agent_id") REFERENCES "core"."agent"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."agent_office" ADD CONSTRAINT "FK_agent_office_office" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_office_ext_ref_office" FOREIGN KEY ("office_id") REFERENCES "core"."office"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office_external_reference" ADD CONSTRAINT "FK_office_ext_ref_external_reference" FOREIGN KEY ("external_reference_id") REFERENCES "core"."external_reference"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "core"."office" ADD CONSTRAINT "FK_office_company" FOREIGN KEY ("company_id") REFERENCES "core"."company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
